# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: branch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='branch.proto',
  package='banking',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62ranch.proto\x12\x07\x62\x61nking\"$\n\x12SyncAccountRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"&\n\x13SyncAccountResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb0\x01\n\x0bSyncAccount\x12O\n\x10PropogateDeposit\x12\x1b.banking.SyncAccountRequest\x1a\x1c.banking.SyncAccountResponse\"\x00\x12P\n\x11PropogateWithdraw\x12\x1b.banking.SyncAccountRequest\x1a\x1c.banking.SyncAccountResponse\"\x00\x62\x06proto3'
)




_SYNCACCOUNTREQUEST = _descriptor.Descriptor(
  name='SyncAccountRequest',
  full_name='banking.SyncAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='banking.SyncAccountRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=61,
)


_SYNCACCOUNTRESPONSE = _descriptor.Descriptor(
  name='SyncAccountResponse',
  full_name='banking.SyncAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='banking.SyncAccountResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['SyncAccountRequest'] = _SYNCACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['SyncAccountResponse'] = _SYNCACCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyncAccountRequest = _reflection.GeneratedProtocolMessageType('SyncAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCACCOUNTREQUEST,
  '__module__' : 'branch_pb2'
  # @@protoc_insertion_point(class_scope:banking.SyncAccountRequest)
  })
_sym_db.RegisterMessage(SyncAccountRequest)

SyncAccountResponse = _reflection.GeneratedProtocolMessageType('SyncAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCACCOUNTRESPONSE,
  '__module__' : 'branch_pb2'
  # @@protoc_insertion_point(class_scope:banking.SyncAccountResponse)
  })
_sym_db.RegisterMessage(SyncAccountResponse)



_SYNCACCOUNT = _descriptor.ServiceDescriptor(
  name='SyncAccount',
  full_name='banking.SyncAccount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=280,
  methods=[
  _descriptor.MethodDescriptor(
    name='PropogateDeposit',
    full_name='banking.SyncAccount.PropogateDeposit',
    index=0,
    containing_service=None,
    input_type=_SYNCACCOUNTREQUEST,
    output_type=_SYNCACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PropogateWithdraw',
    full_name='banking.SyncAccount.PropogateWithdraw',
    index=1,
    containing_service=None,
    input_type=_SYNCACCOUNTREQUEST,
    output_type=_SYNCACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYNCACCOUNT)

DESCRIPTOR.services_by_name['SyncAccount'] = _SYNCACCOUNT

# @@protoc_insertion_point(module_scope)
