# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import branch_pb2 as branch__pb2


class SyncAccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PropogateDeposit = channel.unary_unary(
                '/banking.SyncAccount/PropogateDeposit',
                request_serializer=branch__pb2.SyncAccountRequest.SerializeToString,
                response_deserializer=branch__pb2.SyncAccountResponse.FromString,
                )
        self.PropogateWithdraw = channel.unary_unary(
                '/banking.SyncAccount/PropogateWithdraw',
                request_serializer=branch__pb2.SyncAccountRequest.SerializeToString,
                response_deserializer=branch__pb2.SyncAccountResponse.FromString,
                )


class SyncAccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PropogateDeposit(self, request, context):
        """Propogate_Deposit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropogateWithdraw(self, request, context):
        """Propogate_Withdraw
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PropogateDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.PropogateDeposit,
                    request_deserializer=branch__pb2.SyncAccountRequest.FromString,
                    response_serializer=branch__pb2.SyncAccountResponse.SerializeToString,
            ),
            'PropogateWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.PropogateWithdraw,
                    request_deserializer=branch__pb2.SyncAccountRequest.FromString,
                    response_serializer=branch__pb2.SyncAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.SyncAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SyncAccount(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PropogateDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.SyncAccount/PropogateDeposit',
            branch__pb2.SyncAccountRequest.SerializeToString,
            branch__pb2.SyncAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PropogateWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.SyncAccount/PropogateWithdraw',
            branch__pb2.SyncAccountRequest.SerializeToString,
            branch__pb2.SyncAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
