# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='banking',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63ustomer.proto\x12\x07\x62\x61nking\x1a\x1bgoogle/protobuf/empty.proto\"Q\n\x0e\x41\x63\x63ountRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\r\n\x05\x63lock\x18\x02 \x01(\x05\x12\x14\n\x07\x65ventId\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_eventId\"b\n\x0f\x41\x63\x63ountResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x05\x12\r\n\x05\x63lock\x18\x03 \x01(\x05\x12\x14\n\x07\x65ventId\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_eventId2\xc7\x01\n\x07\x41\x63\x63ount\x12;\n\x05Query\x12\x16.google.protobuf.Empty\x1a\x18.banking.AccountResponse\"\x00\x12>\n\x07\x44\x65posit\x12\x17.banking.AccountRequest\x1a\x18.banking.AccountResponse\"\x00\x12?\n\x08Withdraw\x12\x17.banking.AccountRequest\x1a\x18.banking.AccountResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ACCOUNTREQUEST = _descriptor.Descriptor(
  name='AccountRequest',
  full_name='banking.AccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='banking.AccountRequest.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='banking.AccountRequest.clock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventId', full_name='banking.AccountRequest.eventId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_eventId', full_name='banking.AccountRequest._eventId',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=56,
  serialized_end=137,
)


_ACCOUNTRESPONSE = _descriptor.Descriptor(
  name='AccountResponse',
  full_name='banking.AccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='banking.AccountResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='banking.AccountResponse.money', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='banking.AccountResponse.clock', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventId', full_name='banking.AccountResponse.eventId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_eventId', full_name='banking.AccountResponse._eventId',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=139,
  serialized_end=237,
)

_ACCOUNTREQUEST.oneofs_by_name['_eventId'].fields.append(
  _ACCOUNTREQUEST.fields_by_name['eventId'])
_ACCOUNTREQUEST.fields_by_name['eventId'].containing_oneof = _ACCOUNTREQUEST.oneofs_by_name['_eventId']
_ACCOUNTRESPONSE.oneofs_by_name['_eventId'].fields.append(
  _ACCOUNTRESPONSE.fields_by_name['eventId'])
_ACCOUNTRESPONSE.fields_by_name['eventId'].containing_oneof = _ACCOUNTRESPONSE.oneofs_by_name['_eventId']
DESCRIPTOR.message_types_by_name['AccountRequest'] = _ACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AccountResponse'] = _ACCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountRequest = _reflection.GeneratedProtocolMessageType('AccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREQUEST,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:banking.AccountRequest)
  })
_sym_db.RegisterMessage(AccountRequest)

AccountResponse = _reflection.GeneratedProtocolMessageType('AccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTRESPONSE,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:banking.AccountResponse)
  })
_sym_db.RegisterMessage(AccountResponse)



_ACCOUNT = _descriptor.ServiceDescriptor(
  name='Account',
  full_name='banking.Account',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=240,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='banking.Account.Query',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_ACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Deposit',
    full_name='banking.Account.Deposit',
    index=1,
    containing_service=None,
    input_type=_ACCOUNTREQUEST,
    output_type=_ACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Withdraw',
    full_name='banking.Account.Withdraw',
    index=2,
    containing_service=None,
    input_type=_ACCOUNTREQUEST,
    output_type=_ACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNT)

DESCRIPTOR.services_by_name['Account'] = _ACCOUNT

# @@protoc_insertion_point(module_scope)
